name: Run tests
on:
  - push
  - pull_request
jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Currently supported Python versions:
        # https://devguide.python.org/#status-of-python-branches
        python-version:
          - '3.6'   # EOL: 2021-12-23
          - '3.7'   # EOL: 2023-06-27
          - '3.8'   # EOL: 2024-10
          - '3.9'   # EOL: 2025-10
          - '3.10'  # EOL: 2026-10
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install pytest mock pylint
      - name: Run tests
        run: |
          python -m pytest -v
      - name: Run lint
        run: |
          python -m pylint -E holepunch

